package pharma.model;

// A POJO for the Supplier_Master table
public class Supplier {
    public static final String STATUS_PENDING = "PENDING";
    public static final String STATUS_APPROVED = "APPROVED";
    public static final String STATUS_REJECTED = "REJECTED";

    private int supplierId; // Primary Key
    private String supplierName;
    private String contactPerson;
    private String address;
    private String email;
    private String phoneNumber;
    private String gstin;
    private String drugLicenseNumber;
    private String paymentTerms;
    private String supplierStatus;
    private java.time.LocalDateTime approvedAt;
    private java.time.LocalDateTime rejectedAt;
    private String remarks;

    // Constructor for creating a new Supplier (ID may be auto-generated by DB)
    public Supplier(String supplierName, String contactPerson, String address, String email, 
                    String phoneNumber, String gstin, String drugLicenseNumber, String paymentTerms) {
        this(supplierName, contactPerson, address, email, phoneNumber, gstin, drugLicenseNumber, paymentTerms,
                STATUS_PENDING, null, null, null);
    }

    public Supplier(String supplierName, String contactPerson, String address, String email,
                    String phoneNumber, String gstin, String drugLicenseNumber, String paymentTerms,
                    String supplierStatus, java.time.LocalDateTime approvedAt,
                    java.time.LocalDateTime rejectedAt, String remarks) {
        this.supplierName = supplierName;
        this.contactPerson = contactPerson;
        this.address = address;
        this.email = email;
        this.phoneNumber = phoneNumber;
        this.gstin = gstin;
        this.drugLicenseNumber = drugLicenseNumber;
        this.paymentTerms = paymentTerms;
        this.supplierStatus = supplierStatus;
        this.approvedAt = approvedAt;
        this.rejectedAt = rejectedAt;
        this.remarks = remarks;
    }

    // Constructor for retrieving a Supplier from the database (includes ID)
    public Supplier(int supplierId, String supplierName, String contactPerson, String address, 
                    String email, String phoneNumber, String gstin, String drugLicenseNumber, 
                    String paymentTerms) {
        this(supplierId, supplierName, contactPerson, address, email, phoneNumber, gstin, drugLicenseNumber,
                paymentTerms, STATUS_PENDING, null, null, null);
    }

    public Supplier(int supplierId, String supplierName, String contactPerson, String address,
                    String email, String phoneNumber, String gstin, String drugLicenseNumber,
                    String paymentTerms, String supplierStatus, java.time.LocalDateTime approvedAt,
                    java.time.LocalDateTime rejectedAt, String remarks) {
        this(supplierName, contactPerson, address, email, phoneNumber, gstin, drugLicenseNumber, paymentTerms,
                supplierStatus, approvedAt, rejectedAt, remarks);
        this.supplierId = supplierId;
    }

    // Default Constructor
    public Supplier() {}

    // --- Getters and Setters ---

    public int getSupplierId() {
        return supplierId;
    }

    // Generally, the ID is set only when retrieving from DB
    public void setSupplierId(int supplierId) { 
        this.supplierId = supplierId;
    }

    public String getSupplierName() {
        return supplierName;
    }

    public void setSupplierName(String supplierName) {
        this.supplierName = supplierName;
    }

    public String getContactPerson() {
        return contactPerson;
    }

    public void setContactPerson(String contactPerson) {
        this.contactPerson = contactPerson;
    }

    public String getAddress() {
        return address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getPhoneNumber() {
        return phoneNumber;
    }

    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }

    public String getGstin() {
        return gstin;
    }

    public void setGstin(String gstin) {
        this.gstin = gstin;
    }

    public String getDrugLicenseNumber() {
        return drugLicenseNumber;
    }

    public void setDrugLicenseNumber(String drugLicenseNumber) {
        this.drugLicenseNumber = drugLicenseNumber;
    }

    public String getPaymentTerms() {
        return paymentTerms;
    }

    public void setPaymentTerms(String paymentTerms) {
        this.paymentTerms = paymentTerms;
    }

    public String getSupplierStatus() {
        return supplierStatus;
    }

    public void setSupplierStatus(String supplierStatus) {
        this.supplierStatus = supplierStatus;
    }

    public java.time.LocalDateTime getApprovedAt() {
        return approvedAt;
    }

    public void setApprovedAt(java.time.LocalDateTime approvedAt) {
        this.approvedAt = approvedAt;
    }

    public java.time.LocalDateTime getRejectedAt() {
        return rejectedAt;
    }

    public void setRejectedAt(java.time.LocalDateTime rejectedAt) {
        this.rejectedAt = rejectedAt;
    }

    public String getRemarks() {
        return remarks;
    }

    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }

}
