package pharma.model;

// A POJO for the Supplier_Master table
public class Supplier {

    private int supplierId; // Primary Key
    private String supplierName;
    private String contactPerson;
    private String address;
    private String email;
    private String phoneNumber;
    private String gstin;
    private String drugLicenseNumber;
    private String paymentTerms;

    // Constructor for creating a new Supplier (ID may be auto-generated by DB)
    public Supplier(String supplierName, String contactPerson, String address, String email, 
                    String phoneNumber, String gstin, String drugLicenseNumber, String paymentTerms) {
        this.supplierName = supplierName;
        this.contactPerson = contactPerson;
        this.address = address;
        this.email = email;
        this.phoneNumber = phoneNumber;
        this.gstin = gstin;
        this.drugLicenseNumber = drugLicenseNumber;
        this.paymentTerms = paymentTerms;
    }

    // Constructor for retrieving a Supplier from the database (includes ID)
    public Supplier(int supplierId, String supplierName, String contactPerson, String address, 
                    String email, String phoneNumber, String gstin, String drugLicenseNumber, 
                    String paymentTerms) {
        this(supplierName, contactPerson, address, email, phoneNumber, gstin, drugLicenseNumber, paymentTerms);
        this.supplierId = supplierId;
    }

    // Default Constructor
    public Supplier() {}

    // --- Getters and Setters ---

    public int getSupplierId() {
        return supplierId;
    }

    // Generally, the ID is set only when retrieving from DB
    public void setSupplierId(int supplierId) { 
        this.supplierId = supplierId;
    }

    public String getSupplierName() {
        return supplierName;
    }

    public void setSupplierName(String supplierName) {
        this.supplierName = supplierName;
    }

    public String getContactPerson() {
        return contactPerson;
    }

    public void setContactPerson(String contactPerson) {
        this.contactPerson = contactPerson;
    }

    public String getAddress() {
        return address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getPhoneNumber() {
        return phoneNumber;
    }

    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }

    public String getGstin() {
        return gstin;
    }

    public void setGstin(String gstin) {
        this.gstin = gstin;
    }

    public String getDrugLicenseNumber() {
        return drugLicenseNumber;
    }

    public void setDrugLicenseNumber(String drugLicenseNumber) {
        this.drugLicenseNumber = drugLicenseNumber;
    }

    public String getPaymentTerms() {
        return paymentTerms;
    }

    public void setPaymentTerms(String paymentTerms) {
        this.paymentTerms = paymentTerms;
    }

}
