-- PostgreSQL v1.1 baseline operational schema.
-- Scope: core SCM, RBAC, procurement, inventory, BOM, production, quality, and audit tables.
-- This script is additive and intended for a dedicated v1.1 PostgreSQL database.
-- It must not be run against the v1 MySQL database.

CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS trigger AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TABLE IF NOT EXISTS supplier_master (
    supplier_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    supplier_name VARCHAR(255) NOT NULL,
    contact_person VARCHAR(255),
    address TEXT,
    email VARCHAR(255),
    phone_number VARCHAR(20),
    gstin VARCHAR(50),
    drug_license_number VARCHAR(100),
    payment_terms VARCHAR(255),
    supplier_status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    approved_at TIMESTAMP,
    rejected_at TIMESTAMP,
    remarks TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_supplier_status
        CHECK (supplier_status IN ('PENDING', 'APPROVED', 'REJECTED', 'SUSPENDED'))
);

CREATE TABLE IF NOT EXISTS supplier_audit_log (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    supplier_id INTEGER NOT NULL REFERENCES supplier_master(supplier_id) ON DELETE RESTRICT ON UPDATE CASCADE,
    action VARCHAR(20) NOT NULL,
    remarks TEXT,
    performed_by VARCHAR(50),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS material_master (
    material_code VARCHAR(50) PRIMARY KEY,
    brand_name VARCHAR(255) NOT NULL,
    generic_name VARCHAR(255),
    manufacturer VARCHAR(255),
    formulation VARCHAR(100),
    strength VARCHAR(100),
    schedule_category VARCHAR(50),
    storage_conditions TEXT,
    reorder_level INTEGER NOT NULL DEFAULT 0,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    preferred_supplier_id INTEGER REFERENCES supplier_master(supplier_id) ON DELETE SET NULL ON UPDATE CASCADE,
    material_type VARCHAR(50) NOT NULL DEFAULT 'FINISHED_GOOD',
    unit_of_measure VARCHAR(50) NOT NULL DEFAULT 'UNIT',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_material_type
        CHECK (material_type IN ('RAW_MATERIAL', 'EXCIPIENT', 'PACKAGING', 'INTERMEDIATE', 'FINISHED_GOOD')),
    CONSTRAINT chk_reorder_level_non_negative CHECK (reorder_level >= 0)
);

CREATE TABLE IF NOT EXISTS location_master (
    location_code VARCHAR(50) PRIMARY KEY,
    location_name VARCHAR(255) NOT NULL,
    description TEXT,
    capacity INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_location_capacity_non_negative CHECK (capacity >= 0)
);

CREATE TABLE IF NOT EXISTS role_master (
    role_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_name VARCHAR(100) UNIQUE NOT NULL,
    description TEXT
);

CREATE TABLE IF NOT EXISTS permission_master (
    permission_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    permission_name VARCHAR(100) UNIQUE NOT NULL,
    module VARCHAR(100),
    description TEXT
);

CREATE TABLE IF NOT EXISTS role_permission (
    role_id INTEGER NOT NULL REFERENCES role_master(role_id) ON DELETE CASCADE,
    permission_id INTEGER NOT NULL REFERENCES permission_master(permission_id) ON DELETE CASCADE,
    PRIMARY KEY (role_id, permission_id)
);

CREATE TABLE IF NOT EXISTS user_master (
    user_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(100) UNIQUE NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    full_name VARCHAR(255),
    role_id INTEGER REFERENCES role_master(role_id) ON DELETE RESTRICT,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS system_audit_trail (
    audit_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER REFERENCES user_master(user_id) ON DELETE SET NULL,
    action_type VARCHAR(100) NOT NULL,
    table_name VARCHAR(100),
    record_id VARCHAR(100),
    old_value TEXT,
    new_value TEXT,
    action_timestamp TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ip_address VARCHAR(100),
    notes TEXT
);

CREATE TABLE IF NOT EXISTS purchase_order (
    po_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    supplier_id INTEGER NOT NULL REFERENCES supplier_master(supplier_id) ON DELETE RESTRICT ON UPDATE CASCADE,
    order_date DATE NOT NULL,
    expected_date DATE,
    actual_delivery_date DATE,
    total_amount NUMERIC(12, 2) NOT NULL DEFAULT 0.00,
    status VARCHAR(50) NOT NULL DEFAULT 'Pending',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_purchase_order_amount_non_negative CHECK (total_amount >= 0)
);

CREATE TABLE IF NOT EXISTS purchase_order_item (
    po_item_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    po_id INTEGER NOT NULL REFERENCES purchase_order(po_id) ON DELETE CASCADE ON UPDATE CASCADE,
    material_code VARCHAR(50) NOT NULL REFERENCES material_master(material_code) ON DELETE RESTRICT ON UPDATE CASCADE,
    quantity NUMERIC(12, 4) NOT NULL,
    unit_price NUMERIC(12, 2) NOT NULL,
    CONSTRAINT chk_po_item_quantity_positive CHECK (quantity > 0),
    CONSTRAINT chk_po_item_unit_price_non_negative CHECK (unit_price >= 0)
);

CREATE TABLE IF NOT EXISTS goods_received_note (
    grn_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    po_id INTEGER NOT NULL REFERENCES purchase_order(po_id) ON DELETE RESTRICT ON UPDATE CASCADE,
    received_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    received_by VARCHAR(255),
    status VARCHAR(50) NOT NULL DEFAULT 'Verified',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS grn_item (
    grn_item_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    grn_id INTEGER NOT NULL REFERENCES goods_received_note(grn_id) ON DELETE CASCADE ON UPDATE CASCADE,
    material_code VARCHAR(50) NOT NULL REFERENCES material_master(material_code) ON DELETE RESTRICT ON UPDATE CASCADE,
    batch_number VARCHAR(100) NOT NULL,
    quantity_received NUMERIC(12, 4) NOT NULL,
    expiry_date DATE NOT NULL,
    CONSTRAINT chk_grn_item_quantity_positive CHECK (quantity_received > 0)
);

CREATE TABLE IF NOT EXISTS bom_header (
    bom_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    material_code VARCHAR(50) NOT NULL REFERENCES material_master(material_code) ON DELETE RESTRICT ON UPDATE CASCADE,
    version_number INTEGER NOT NULL DEFAULT 1,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    effective_date DATE NOT NULL,
    description TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_bom_material_version UNIQUE (material_code, version_number),
    CONSTRAINT chk_bom_version_positive CHECK (version_number > 0)
);

CREATE TABLE IF NOT EXISTS bom_details (
    bom_detail_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bom_id INTEGER NOT NULL REFERENCES bom_header(bom_id) ON DELETE CASCADE ON UPDATE CASCADE,
    ingredient_material_code VARCHAR(50) NOT NULL REFERENCES material_master(material_code) ON DELETE RESTRICT ON UPDATE CASCADE,
    required_qty NUMERIC(12, 4) NOT NULL,
    uom VARCHAR(20) NOT NULL,
    sequence_number INTEGER NOT NULL DEFAULT 0,
    notes TEXT,
    CONSTRAINT chk_bom_detail_required_qty_positive CHECK (required_qty > 0)
);

CREATE TABLE IF NOT EXISTS production_order (
    order_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch_number VARCHAR(100) UNIQUE NOT NULL,
    bom_id INTEGER NOT NULL REFERENCES bom_header(bom_id) ON DELETE RESTRICT ON UPDATE CASCADE,
    planned_qty NUMERIC(12, 4) NOT NULL,
    actual_qty NUMERIC(12, 4),
    status VARCHAR(50) NOT NULL DEFAULT 'Planned',
    production_date DATE,
    completed_date DATE,
    created_by INTEGER REFERENCES user_master(user_id) ON DELETE RESTRICT,
    notes TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_production_planned_qty_positive CHECK (planned_qty > 0),
    CONSTRAINT chk_production_actual_qty_non_negative CHECK (actual_qty IS NULL OR actual_qty >= 0)
);

CREATE TABLE IF NOT EXISTS stock_inventory (
    stock_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    material_code VARCHAR(50) NOT NULL REFERENCES material_master(material_code) ON DELETE RESTRICT ON UPDATE CASCADE,
    location_code VARCHAR(50) NOT NULL REFERENCES location_master(location_code) ON DELETE RESTRICT ON UPDATE CASCADE,
    batch_number VARCHAR(100) NOT NULL,
    quantity NUMERIC(12, 4) NOT NULL DEFAULT 0.0000,
    reserved_quantity NUMERIC(12, 4) NOT NULL DEFAULT 0.0000,
    available_quantity NUMERIC(12, 4) GENERATED ALWAYS AS (quantity - reserved_quantity) STORED,
    unit_cost NUMERIC(12, 2),
    mfg_date DATE,
    exp_date DATE,
    qc_status VARCHAR(50) NOT NULL DEFAULT 'APPROVED',
    parent_batch_id TEXT,
    production_order_id INTEGER REFERENCES production_order(order_id) ON DELETE SET NULL ON UPDATE CASCADE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_stock_material_location_batch UNIQUE (material_code, location_code, batch_number),
    CONSTRAINT chk_stock_quantity_non_negative CHECK (quantity >= 0),
    CONSTRAINT chk_stock_reserved_quantity_non_negative CHECK (reserved_quantity >= 0),
    CONSTRAINT chk_stock_reserved_not_above_quantity CHECK (reserved_quantity <= quantity)
);

CREATE TABLE IF NOT EXISTS inventory_transaction (
    transaction_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    material_code VARCHAR(50) REFERENCES material_master(material_code) ON DELETE RESTRICT ON UPDATE CASCADE,
    batch_number VARCHAR(100),
    location_code VARCHAR(50) REFERENCES location_master(location_code) ON DELETE RESTRICT ON UPDATE CASCADE,
    transaction_type VARCHAR(50) NOT NULL,
    quantity NUMERIC(12, 4) NOT NULL,
    reference_type VARCHAR(50),
    reference_id VARCHAR(50),
    performed_by INTEGER REFERENCES user_master(user_id) ON DELETE RESTRICT ON UPDATE CASCADE,
    transaction_timestamp TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    notes TEXT
);

CREATE TABLE IF NOT EXISTS production_material_consumption (
    consumption_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    production_order_id INTEGER REFERENCES production_order(order_id) ON DELETE CASCADE ON UPDATE CASCADE,
    material_code VARCHAR(50) REFERENCES material_master(material_code) ON DELETE RESTRICT ON UPDATE CASCADE,
    batch_number VARCHAR(100),
    required_qty NUMERIC(12, 4),
    consumed_qty NUMERIC(12, 4),
    uom VARCHAR(20),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS production_batch (
    batch_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    production_order_id INTEGER REFERENCES production_order(order_id) ON DELETE CASCADE ON UPDATE CASCADE,
    material_code VARCHAR(50) REFERENCES material_master(material_code) ON DELETE RESTRICT ON UPDATE CASCADE,
    batch_number VARCHAR(100) UNIQUE,
    quantity NUMERIC(12, 4),
    mfg_date DATE,
    expiry_date DATE,
    qc_status VARCHAR(50) NOT NULL DEFAULT 'QUARANTINE',
    location_code VARCHAR(50) REFERENCES location_master(location_code) ON DELETE RESTRICT ON UPDATE CASCADE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS batch_genealogy (
    genealogy_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parent_batch VARCHAR(100),
    child_batch VARCHAR(100),
    production_order_id INTEGER REFERENCES production_order(order_id) ON DELETE CASCADE ON UPDATE CASCADE,
    relationship_type VARCHAR(50),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS event_log (
    event_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_type VARCHAR(100) NOT NULL,
    entity_type VARCHAR(100),
    entity_id VARCHAR(100),
    event_timestamp TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    details TEXT,
    status VARCHAR(50)
);

CREATE TABLE IF NOT EXISTS qa_records (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch_number VARCHAR(100) NOT NULL,
    test_type VARCHAR(100) NOT NULL,
    result VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    tested_by VARCHAR(255),
    tested_at TIMESTAMP,
    notes TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_qa_result CHECK (result IN ('PASS', 'FAIL', 'PENDING'))
);

CREATE TABLE IF NOT EXISTS deviation_records (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch_number VARCHAR(100),
    description TEXT NOT NULL,
    criticality VARCHAR(20) NOT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'OPEN',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_deviation_criticality CHECK (criticality IN ('MINOR', 'MAJOR', 'CRITICAL')),
    CONSTRAINT chk_deviation_status CHECK (status IN ('OPEN', 'INVESTIGATING', 'CLOSED'))
);

CREATE TABLE IF NOT EXISTS capa_records (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    deviation_id INTEGER REFERENCES deviation_records(id) ON DELETE CASCADE,
    action_plan TEXT NOT NULL,
    due_date DATE,
    status VARCHAR(30) NOT NULL DEFAULT 'OPEN',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_capa_status CHECK (status IN ('OPEN', 'IMPLEMENTED', 'VERIFIED'))
);

CREATE TABLE IF NOT EXISTS compliance_records (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reference_id VARCHAR(100),
    rule_checked VARCHAR(255) NOT NULL,
    is_compliant BOOLEAN NOT NULL,
    checked_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    notes TEXT
);

CREATE INDEX IF NOT EXISTS idx_material_preferred_supplier ON material_master(preferred_supplier_id);
CREATE INDEX IF NOT EXISTS idx_purchase_order_supplier ON purchase_order(supplier_id);
CREATE INDEX IF NOT EXISTS idx_purchase_order_status ON purchase_order(status);
CREATE INDEX IF NOT EXISTS idx_purchase_order_item_po ON purchase_order_item(po_id);
CREATE INDEX IF NOT EXISTS idx_grn_po ON goods_received_note(po_id);
CREATE INDEX IF NOT EXISTS idx_grn_item_grn ON grn_item(grn_id);
CREATE INDEX IF NOT EXISTS idx_stock_material ON stock_inventory(material_code);
CREATE INDEX IF NOT EXISTS idx_stock_location ON stock_inventory(location_code);
CREATE INDEX IF NOT EXISTS idx_stock_batch ON stock_inventory(batch_number);
CREATE INDEX IF NOT EXISTS idx_inventory_transaction_material ON inventory_transaction(material_code);
CREATE INDEX IF NOT EXISTS idx_inventory_transaction_reference ON inventory_transaction(reference_type, reference_id);
CREATE INDEX IF NOT EXISTS idx_event_log_type_time ON event_log(event_type, event_timestamp);
CREATE INDEX IF NOT EXISTS idx_system_audit_action_time ON system_audit_trail(action_type, action_timestamp);
CREATE INDEX IF NOT EXISTS idx_qa_records_batch ON qa_records(batch_number);

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'trg_supplier_master_updated_at') THEN
        CREATE TRIGGER trg_supplier_master_updated_at
        BEFORE UPDATE ON supplier_master
        FOR EACH ROW EXECUTE FUNCTION set_updated_at();
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'trg_material_master_updated_at') THEN
        CREATE TRIGGER trg_material_master_updated_at
        BEFORE UPDATE ON material_master
        FOR EACH ROW EXECUTE FUNCTION set_updated_at();
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'trg_location_master_updated_at') THEN
        CREATE TRIGGER trg_location_master_updated_at
        BEFORE UPDATE ON location_master
        FOR EACH ROW EXECUTE FUNCTION set_updated_at();
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'trg_user_master_updated_at') THEN
        CREATE TRIGGER trg_user_master_updated_at
        BEFORE UPDATE ON user_master
        FOR EACH ROW EXECUTE FUNCTION set_updated_at();
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'trg_purchase_order_updated_at') THEN
        CREATE TRIGGER trg_purchase_order_updated_at
        BEFORE UPDATE ON purchase_order
        FOR EACH ROW EXECUTE FUNCTION set_updated_at();
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'trg_bom_header_updated_at') THEN
        CREATE TRIGGER trg_bom_header_updated_at
        BEFORE UPDATE ON bom_header
        FOR EACH ROW EXECUTE FUNCTION set_updated_at();
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'trg_production_order_updated_at') THEN
        CREATE TRIGGER trg_production_order_updated_at
        BEFORE UPDATE ON production_order
        FOR EACH ROW EXECUTE FUNCTION set_updated_at();
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'trg_stock_inventory_updated_at') THEN
        CREATE TRIGGER trg_stock_inventory_updated_at
        BEFORE UPDATE ON stock_inventory
        FOR EACH ROW EXECUTE FUNCTION set_updated_at();
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'trg_deviation_records_updated_at') THEN
        CREATE TRIGGER trg_deviation_records_updated_at
        BEFORE UPDATE ON deviation_records
        FOR EACH ROW EXECUTE FUNCTION set_updated_at();
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'trg_capa_records_updated_at') THEN
        CREATE TRIGGER trg_capa_records_updated_at
        BEFORE UPDATE ON capa_records
        FOR EACH ROW EXECUTE FUNCTION set_updated_at();
    END IF;
END $$;
