-- PostgreSQL v1.1 agentic and AI/RAG schema.
-- Scope: supplier risk, AI decisions, risk assessments, and knowledge metadata.

CREATE TABLE IF NOT EXISTS supplier_delivery_history (
    history_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    supplier_id INTEGER NOT NULL REFERENCES supplier_master(supplier_id) ON DELETE RESTRICT ON UPDATE CASCADE,
    material_code VARCHAR(50) NOT NULL REFERENCES material_master(material_code) ON DELETE RESTRICT ON UPDATE CASCADE,
    po_id INTEGER REFERENCES purchase_order(po_id) ON DELETE SET NULL ON UPDATE CASCADE,
    expected_date DATE,
    actual_date DATE,
    on_time BOOLEAN,
    quantity_ordered NUMERIC(12, 4),
    quantity_received NUMERIC(12, 4),
    rejection_flag BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_supplier_delivery_ordered_non_negative
        CHECK (quantity_ordered IS NULL OR quantity_ordered >= 0),
    CONSTRAINT chk_supplier_delivery_received_non_negative
        CHECK (quantity_received IS NULL OR quantity_received >= 0)
);

CREATE TABLE IF NOT EXISTS risk_assessments (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    context_type VARCHAR(100) NOT NULL,
    context_id VARCHAR(100) NOT NULL,
    risk_category VARCHAR(100),
    risk_score NUMERIC(5, 4) NOT NULL,
    severity VARCHAR(20) NOT NULL,
    drivers TEXT,
    mitigation_notes TEXT,
    assessed_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_risk_score_range CHECK (risk_score >= 0 AND risk_score <= 1),
    CONSTRAINT chk_risk_severity CHECK (severity IN ('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', 'UNKNOWN'))
);

CREATE TABLE IF NOT EXISTS ai_decisions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transaction_id VARCHAR(36) NOT NULL,
    agent_name VARCHAR(100),
    task_type VARCHAR(100),
    prompt_summary TEXT,
    response_summary TEXT,
    raw_output TEXT,
    confidence_score NUMERIC(5, 4),
    requires_human_review BOOLEAN NOT NULL DEFAULT FALSE,
    decision_applied BOOLEAN NOT NULL DEFAULT FALSE,
    status VARCHAR(50) NOT NULL DEFAULT 'PENDING',
    reviewed_by INTEGER REFERENCES user_master(user_id) ON DELETE SET NULL,
    review_reason TEXT,
    reviewed_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_ai_confidence_range
        CHECK (confidence_score IS NULL OR (confidence_score >= 0 AND confidence_score <= 1)),
    CONSTRAINT chk_ai_decision_status
        CHECK (status IN ('PENDING', 'APPROVED', 'REJECTED', 'FAILED', 'APPLIED'))
);

CREATE TABLE IF NOT EXISTS knowledge_documents (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    document_type VARCHAR(50) NOT NULL,
    version VARCHAR(50),
    file_path VARCHAR(500),
    checksum VARCHAR(128),
    ingested_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT chk_knowledge_document_type
        CHECK (document_type IN ('SOP', 'SPECIFICATION', 'POLICY', 'REGULATION', 'DEVIATION', 'OTHER'))
);

CREATE TABLE IF NOT EXISTS document_chunks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id INTEGER NOT NULL REFERENCES knowledge_documents(id) ON DELETE CASCADE,
    chunk_index INTEGER NOT NULL,
    content TEXT NOT NULL,
    embedding_id VARCHAR(255),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_document_chunk_index UNIQUE (document_id, chunk_index),
    CONSTRAINT chk_document_chunk_index_non_negative CHECK (chunk_index >= 0)
);

CREATE INDEX IF NOT EXISTS idx_supplier_delivery_supplier ON supplier_delivery_history(supplier_id);
CREATE INDEX IF NOT EXISTS idx_supplier_delivery_material ON supplier_delivery_history(material_code);
CREATE INDEX IF NOT EXISTS idx_supplier_delivery_po ON supplier_delivery_history(po_id);
CREATE INDEX IF NOT EXISTS idx_risk_assessments_context ON risk_assessments(context_type, context_id);
CREATE INDEX IF NOT EXISTS idx_risk_assessments_assessed_at ON risk_assessments(assessed_at);
CREATE INDEX IF NOT EXISTS idx_ai_decisions_transaction ON ai_decisions(transaction_id);
CREATE INDEX IF NOT EXISTS idx_ai_decisions_status ON ai_decisions(status);
CREATE INDEX IF NOT EXISTS idx_ai_decisions_created_at ON ai_decisions(created_at);
CREATE INDEX IF NOT EXISTS idx_knowledge_documents_type ON knowledge_documents(document_type);
CREATE INDEX IF NOT EXISTS idx_document_chunks_document ON document_chunks(document_id);
CREATE INDEX IF NOT EXISTS idx_document_chunks_embedding ON document_chunks(embedding_id);
