-- PostgreSQL v1.1 observability schema.
-- Scope: optional persisted event stream for JADE/LangChain4j observability overlay.
-- The first implementation can use an in-memory buffer; these tables support later retention and history.

CREATE TABLE IF NOT EXISTS agent_events (
    event_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transaction_id VARCHAR(36),
    event_timestamp TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    agent_name VARCHAR(100),
    action VARCHAR(100),
    status VARCHAR(50),
    severity VARCHAR(20) NOT NULL DEFAULT 'INFO',
    phase VARCHAR(100),
    message TEXT NOT NULL,
    payload_summary TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_agent_event_severity
        CHECK (severity IN ('TRACE', 'DEBUG', 'INFO', 'WARN', 'ERROR', 'DECISION')),
    CONSTRAINT chk_agent_event_status
        CHECK (status IS NULL OR status IN ('SUCCESS', 'PARTIAL_SUCCESS', 'FAILURE', 'TIMEOUT', 'VETO', 'STARTED', 'RUNNING'))
);

CREATE TABLE IF NOT EXISTS agent_event_details (
    event_id BIGINT PRIMARY KEY REFERENCES agent_events(event_id) ON DELETE CASCADE,
    trace JSONB,
    errors JSONB,
    payload JSONB
);

CREATE INDEX IF NOT EXISTS idx_agent_events_transaction ON agent_events(transaction_id);
CREATE INDEX IF NOT EXISTS idx_agent_events_agent ON agent_events(agent_name);
CREATE INDEX IF NOT EXISTS idx_agent_events_action ON agent_events(action);
CREATE INDEX IF NOT EXISTS idx_agent_events_severity ON agent_events(severity);
CREATE INDEX IF NOT EXISTS idx_agent_events_timestamp ON agent_events(event_timestamp);
CREATE INDEX IF NOT EXISTS idx_agent_event_details_trace ON agent_event_details USING GIN (trace);
CREATE INDEX IF NOT EXISTS idx_agent_event_details_errors ON agent_event_details USING GIN (errors);
